name: Fetch latest shaw outages data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "1,16,31,46 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Fetches repo
        uses: actions/checkout@v2
      - name: Installs python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Installs dependencies
        run: |-
          python -m pip install -r requirements.txt
      - name: Generate jsons
        run: |-
          python scraper.py
      - name: Add results to config
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A *.json
          timestamp=$(date -u -Is)
          git commit -m "Update data on ${timestamp}" || exit 0
          git push
